ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    (1..1).each do |i|
        config.vm.define "node-#{i}" do |host|
            host.vm.box = "oraclelinux/8"
            host.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
            host.vm.hostname = "node#{i}.local"
            host.vm.provider "libvirt" do |libvirt|
                libvirt.memory = 2048
                libvirt.cpus = 2
                libvirt.qemu_use_session = false
            end
            host.vm.provision "shell", inline: <<-SHELL
            sudo yum install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
            sudo yum --enablerepo elrepo-kernel install kernel-ml -y
            sudo grub2-mkconfig -o /boot/grub2/grub.cfg
            sudo grub2-set-default 0
            sudo reboot
            SHELL
        end
    end
end
