ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

disk_controller = 'SATA Controller'

MACHINES = {
  :zfs => {
    :box_name => "oraclelinux/7",
    :box_url => "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json",
    :disks => {
            :sata1 => {
                :dfile => './sata1.vdi',
                :size => 512,
                :port => 1
            },
            :sata2 => {
                :dfile => './sata2.vdi',
                :size => 512,
                :port => 2
            },
            :sata3 => {
                :dfile => './sata3.vdi',
                :size => 512,
                :port => 3
            },
            :sata4 => {
                :dfile => './sata4.vdi',
                :size => 512, 
                :port => 4
            },
            :sata5 => {
                :dfile => './sata5.vdi',
                :size => 512,
                :port => 5
            },
            :sata6 => {
                :dfile => './sata6.vdi',
                :size => 512,
                :port => 6
            },
            :sata7 => {
                :dfile => './sata7.vdi',
                :size => 512, 
                :port => 7
            },
            :sata8 => {
                :dfile => './sata8.vdi',
                :size => 512, 
                :port => 8
            },
        }
  },
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

            box.vm.box = boxconfig[:box_name]
            box.vm.box_url = boxconfig[:box_url]
            box.vm.host_name = boxname.to_s
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "4"]
                needsController = false
                boxconfig[:disks].each do |dname, dconf|
                    unless File.exist?(dconf[:dfile])
                        vb.customize ['createmedium', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                        needsController =  true
                    end
                end
                if needsController == true
                    # vb.customize ["storagectl", :id, "--name", disk_controller, "--add", "sata" ]
                    boxconfig[:disks].each do |dname, dconf|
                        vb.customize ['storageattach', :id,  '--storagectl', disk_controller, '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                    end
                end
            end
 	        box.vm.provision "shell", inline: <<-SHELL
                yum install -y https://zfsonlinux.org/epel/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm
                rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-openzfs-el-7
                yum install -y kernel-devel
                yum install -y zfs
                modprobe zfs
            SHELL
        end
    end
end
